version: '2'

services:
  drone-server:
    image: drone/drone:1
    container_name: drone
    ports:
      - 4096:80
        # - 443:443
    volumes:
      - ./data:/data
    restart: always
    environment:
      - DRONE_SERVER_HOST=DRONE_HOST
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=DRONE_SECRET
      - DRONE_AGENTS_ENABLED=true
      - DRONE_ADMIN=MY_ACCOUNT
      - DRONE_LOG_TRACE-true
      # GitHub Config
      - DRONE_GITEA_SERVER=https://GITEA_HOST
      - DRONE_GITEA_CLIENT_ID=ID
      - DRONE_GITEA_CLIENT_SECRET=SECRET

  drone-agent:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=DRONE_SECRET
      - DRONE_RUNNER_CAPACITY=3
      - DRONE_LOG_TRACE-true
